### ISSUE TITLE
Open invitation to join Hyperloot PR & Media working group

### ISSUE THREAD

**Issue by hyperloot** [HyperLootProtocol/Publications#1]
Media planning thesises:

- accordance to the  DAO principles
- involving the best people to the publcation workflow
- open publication plan with opportunity for the community to get involved into writing, translating and distributing content
- Token rewards for participation (token are locked up for a month)
- Invite large blockchain and gaming media to participate

**Comment by trelobit** [comment]
draft with russian text https://docs.google.com/document/d/1RaTc4kdUDcGBSvmbrc2XKbM4kBFwQBX14COFiBu3C64/edit?usp=sharing

**Comment by trelobit** [comment]
Nick, please do a review and translation of rewards section

link to draft on medium https://medium.com/@danilapermyakov/open-invitation-to-join-hyperloot-pr-media-working-group-13210ba27ed3

**Comment by trelobit** [comment]
thanks @PonyUnicorn repost it to the reddit please
