### ISSUE TITLE
Hyperloot manifesto

### ISSUE THREAD

**Issue by hyperloot** [HyperLootProtocol/Publications#2]
v.1 https://docs.google.com/document/d/1w6L-n2giYrEuM9kOiTMaRTd3oydVc0mm7sXI-i5LLmg/edit?usp=sharing

v.2 https://docs.google.com/document/d/1F9cniMrbBVvrwRsZHjcZPE9k5Rlavpxdugi0c-K4xPw/edit?usp=sharing

v.3 https://docs.google.com/document/d/10FNdK1wnKbboeDyBuGlZZ09F7e7Qq3AG45AT0_N_bYg/edit?usp=sharing 

v.4 https://docs.google.com/document/d/1qCnJ2cyGMstoIY8voh2YQPoyIt1ENXa5X-USiqbTxTo/edit?usp=sharing

**Comment by hyperloot** [comment]
@PonyUnicorn need some help with translation!

**Comment by PonyUnicorn** [comment]
Translation for v 4

https://docs.google.com/document/d/168HTdkjTkF54QgdvrRFy1rC9VnLhI9E3_PNg72sErpw/edit

**Comment by trelobit** [comment]
![hyperloot_manifesto](https://user-images.githubusercontent.com/30324843/42934591-3f0ef970-8b50-11e8-87c4-d0ec02cf5c19.jpg)
