### ISSUE TITLE
Token announce

### ISSUE THREAD

**Issue by alexva244** [HyperLootProtocol/Publications#6]
https://docs.google.com/document/d/14fQr_LfaZNktyqgjqUFAJByWgabQCbXdNOw5wX83p7c/edit

**Comment by PonyUnicorn** [comment]
https://docs.google.com/document/d/1q1XRXhdU7ZQDv9_0Gr0K-J7YuPnzuEzNisAFc2lwzDc/edit

Translation

**Comment by hyperloot** [comment]
Published https://medium.com/hyperloot-protocol/token-announce-bb908814f95c
